"use client";

import Link from "next/link";
import { useCallback, useEffect, useRef, useState, type ChangeEvent } from "react";

import { Button, IconButton } from "@/shared/ui";

import { deleteProjectDocument, loadProject, loadProjectDocuments, uploadProjectDocument } from "../api/projects";
import type { ProjectDocument, ProjectView } from "../model/types";

export function ProjectDocumentsPage({ projectId }: Readonly<{ projectId: string }>) {
  const [project,setProject]=useState<ProjectView|null>(null);const [documents,setDocuments]=useState<ProjectDocument[]>([]);const [canUpload,setCanUpload]=useState(false);const [state,setState]=useState<"loading"|"ready"|"error">("loading");const [error,setError]=useState("");const [pending,setPending]=useState(false);const inputRef=useRef<HTMLInputElement>(null);
  const load=useCallback(async(signal?:AbortSignal)=>{setState("loading");try{const [projectValue,list]=await Promise.all([loadProject(projectId,signal),loadProjectDocuments(projectId,signal)]);setProject(projectValue);setDocuments(list.items);setCanUpload(list.canUpload);setState("ready")}catch(reason){if(reason instanceof DOMException&&reason.name==="AbortError")return;setError(reason instanceof Error?reason.message:"Не удалось загрузить документы");setState("error")}},[projectId]);
  useEffect(()=>{const controller=new AbortController();queueMicrotask(()=>{if(!controller.signal.aborted)void load(controller.signal)});return()=>controller.abort()},[load]);
  async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value="";if(!file)return;if(file.size>10*1024*1024){setError("Размер файла не должен превышать 10 МБ");return}setPending(true);setError("");try{const document=await uploadProjectDocument(projectId,file);setDocuments((items)=>[document,...items])}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось загрузить документ")}finally{setPending(false)}}
  async function remove(document:ProjectDocument){if(!window.confirm(`Удалить документ «${document.name}»?`))return;setError("");try{await deleteProjectDocument(projectId,document.id);setDocuments((items)=>items.filter((item)=>item.id!==document.id))}catch(reason){setError(reason instanceof Error?reason.message:"Не удалось удалить документ")}}
  if(state==="loading")return <div aria-label="Загрузка документов" className="h-96 animate-pulse border border-border bg-surface" role="status"/>;
  if(state==="error"||!project)return <div className="border border-red-700/40 bg-surface p-8" role="alert"><h1 className="font-display text-4xl">Документы не открылись</h1><p className="mt-3 text-secondary">{error}</p><Button className="mt-6" onClick={()=>void load()}>Повторить</Button></div>;
  return <section aria-label="Документы проекта" data-cy="project-documents-page"><nav aria-label="Хлебные крошки" className="flex flex-wrap items-center gap-2 text-xs text-secondary"><Link href="/account">Проекты</Link><span>/</span><Link href={`/account/projects/${encodeURIComponent(projectId)}`}>{project.name}</Link><span>/</span><span aria-current="page">Документы</span></nav><div className="mt-7 flex items-center gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-action">Файлы проекта</p><h1 className="mt-2 font-display text-5xl">Документация</h1></div>{canUpload?<><input accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png,.zip" className="sr-only" onChange={(event)=>void upload(event)} ref={inputRef} type="file"/><IconButton aria-label="Загрузить документ" className="ml-auto size-10 border-icon-button-border bg-icon-button text-icon-button-text" disabled={pending} onClick={()=>inputRef.current?.click()} tooltip="Загрузить документ"><UploadIcon/></IconButton></>:null}</div><p className="mt-4 max-w-2xl text-sm leading-6 text-secondary">Планы, чертежи, ведомости и другие файлы проекта. Максимальный размер одного файла — 10 МБ.</p>{error?<p className="mt-5 text-sm text-red-700" role="alert">{error}</p>:null}<div className="mt-8 border border-border bg-surface">{documents.length===0?<div className="p-10 text-center"><h2 className="text-xl font-medium">Документов пока нет</h2><p className="mt-2 text-sm text-secondary">Загрузите первый файл проектной документации.</p></div>:<ul>{documents.map((document)=><li className="flex items-center gap-4 border-b border-border p-4 last:border-0" key={document.id}><FileIcon/><div className="min-w-0 flex-1"><a className="block truncate text-sm font-medium underline decoration-action underline-offset-4" href={`/api/v1/projects/${encodeURIComponent(projectId)}/documents/${encodeURIComponent(document.id)}`} rel="noreferrer" target="_blank">{document.name}</a><p className="mt-1 text-xs text-secondary">{formatSize(document.sizeBytes)} · {new Intl.DateTimeFormat("ru-RU",{dateStyle:"medium"}).format(new Date(document.createdAt))}</p></div>{document.canDelete?<IconButton aria-label={`Удалить ${document.name}`} className="size-9 border-icon-button-border bg-icon-button text-red-700" onClick={()=>void remove(document)} tooltip="Удалить"><TrashIcon/></IconButton>:null}</li>)}</ul>}</div></section>
}
function formatSize(value:number){if(value<1024)return `${value} Б`;if(value<1024*1024)return `${Math.ceil(value/1024)} КБ`;return `${(value/(1024*1024)).toFixed(1)} МБ`}
function UploadIcon(){return <svg aria-hidden="true" className="size-4" fill="none" viewBox="0 0 20 20"><path d="M10 13V3m0 0L6 7m4-4 4 4M4 12v4h12v-4" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5"/></svg>}
function FileIcon(){return <svg aria-hidden="true" className="size-8 shrink-0 text-secondary" fill="none" viewBox="0 0 32 32"><path d="M8 4h11l5 5v19H8z" stroke="currentColor"/><path d="M19 4v6h5" stroke="currentColor"/></svg>}
function TrashIcon(){return <svg aria-hidden="true" className="size-4" fill="none" viewBox="0 0 20 20"><path d="M4 6h12M8 3h4l1 3H7l1-3Zm-2 3 1 11h6l1-11" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.4"/></svg>}
