"use client";

import Link from "next/link";
import { useEffect, useMemo, useState, type FormEvent } from "react";

import { Button, DatePicker, Dialog, IconButton, Input, Select, Textarea } from "@/shared/ui";

import { createProjectMaterial, deleteProjectMaterial, loadProject, loadProjectExpenses, loadProjectMaterials, ProjectApiError, updateProjectMaterial } from "../api/projects";
import type { MaterialCategory, MaterialDeliveryStatus, MaterialPaymentStatus, ProjectExpense, ProjectMaterial, ProjectMaterialInput, ProjectMaterialList, ProjectView } from "../model/types";
import { ContextChatAction } from "./contextChatAction";
import { formatMoney, parseMoney } from "./projectFinance";

const categoryOptions = [{ label: "Материалы", value: "materials" }, { label: "Мебель", value: "furniture" }, { label: "Доставка", value: "delivery" }, { label: "Монтаж", value: "installation" }, { label: "Другое", value: "other" }] as const;
const deliveryOptions = [{ label: "Ожидается", value: "expected" }, { label: "Частично доставлено", value: "partially_delivered" }, { label: "Доставлено", value: "delivered" }, { label: "Установлено", value: "installed" }, { label: "Отменено", value: "cancelled" }] as const;
const paymentOptions = [{ label: "Не оплачено", value: "unpaid" }, { label: "Частично оплачено", value: "partial" }, { label: "Оплачено", value: "paid" }] as const;
type MaterialDisplayMode = "list" | "table";

export function ProjectMaterialsPage({ projectId }: Readonly<{ projectId: string }>) {
  const [project, setProject] = useState<ProjectView | null>(null);
  const [list, setList] = useState<ProjectMaterialList | null>(null);
  const [expenses, setExpenses] = useState<ProjectExpense[]>([]);
  const [state, setState] = useState<"loading" | "ready" | "error">("loading");
  const [error, setError] = useState("");
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState<MaterialCategory | "all">("all");
  const [displayMode, setDisplayMode] = useState<MaterialDisplayMode>("table");
  const [editing, setEditing] = useState<ProjectMaterial | "new" | null>(null);
  const [deleting, setDeleting] = useState<ProjectMaterial | null>(null);
  const [notice, setNotice] = useState("");

  async function refresh(signal?: AbortSignal) {
    setState("loading"); setError("");
    try {
      const [nextProject, nextList, expenseList] = await Promise.all([loadProject(projectId, signal), loadProjectMaterials(projectId, signal), loadProjectExpenses(projectId, signal)]);
      setProject(nextProject); setList(nextList); setExpenses(expenseList.items); setState("ready");
    } catch (reason) {
      if (reason instanceof DOMException && reason.name === "AbortError") return;
      setError(reason instanceof ProjectApiError && reason.status === 404 ? "Проект не найден или у вас нет доступа к материалам" : reason instanceof Error ? reason.message : "Не удалось загрузить материалы"); setState("error");
    }
  }

  useEffect(() => {
    const controller = new AbortController();
    void Promise.all([loadProject(projectId, controller.signal), loadProjectMaterials(projectId, controller.signal), loadProjectExpenses(projectId, controller.signal)]).then(([nextProject, nextList, expenseList]) => {
      setProject(nextProject); setList(nextList); setExpenses(expenseList.items); setState("ready");
    }).catch((reason: unknown) => {
      if (reason instanceof DOMException && reason.name === "AbortError") return;
      setError(reason instanceof ProjectApiError && reason.status === 404 ? "Проект не найден или у вас нет доступа к материалам" : reason instanceof Error ? reason.message : "Не удалось загрузить материалы"); setState("error");
    });
    return () => controller.abort();
  }, [projectId]);

  const visible = useMemo(() => {
    const needle = query.trim().toLocaleLowerCase("ru");
    return (list?.items ?? []).filter((item) => (category === "all" || item.category === category) && (!needle || `${item.name} ${item.supplierName} ${item.contactInfo ?? ""} ${item.contractReference ?? ""}`.toLocaleLowerCase("ru").includes(needle)));
  }, [category, list?.items, query]);

  if (state === "loading") return <div aria-label="Загрузка материалов" className="h-96 animate-pulse border border-border bg-surface" role="status" />;
  if (state === "error" || !project || !list) return <div className="border border-red-700/40 bg-surface p-8" role="alert"><h1 className="font-display text-4xl">Материалы не открылись</h1><p className="mt-3 text-secondary">{error}</p><Button className="mt-6" onClick={() => void refresh()}>Повторить</Button></div>;

  const totals = list.items.reduce((value, item) => ({ contract: value.contract + item.contractAmountMinor, paid: value.paid + item.paidAmountMinor, remaining: value.remaining + item.remainingAmountMinor }), { contract: 0, paid: 0, remaining: 0 });
  return <section aria-labelledby="project-materials-title" data-cy="project-materials-page">
    <nav aria-label="Хлебные крошки" className="text-xs text-secondary"><Link href={`/account/projects/${encodeURIComponent(project.id)}`}>{project.name}</Link><span aria-hidden="true" className="px-2">/</span><span aria-current="page">Материалы</span></nav>
    <header className="mt-7 flex items-center justify-between gap-5">
      <div><h1 className="sr-only" id="project-materials-title">Материалы</h1><p className="max-w-2xl text-sm leading-6 text-secondary">Поставщики, договоры, оплаты и сроки доставки — в одном связанном реестре.</p></div>
      {list.canCreate ? <IconButton aria-label="Добавить материал" className="size-10 shrink-0 border-icon-button-border bg-icon-button text-icon-button-text hover:border-action hover:bg-icon-button-hover" data-cy="add-project-material" onClick={() => { setNotice(""); setEditing("new"); }} tooltip="Добавить материал" tooltipAlign="end"><PlusIcon /></IconButton> : null}
    </header>
    {list.canViewFinancialInformation ? <div className="mt-8 grid gap-px border border-border bg-border tablet:grid-cols-3"><Metric label="Сумма договоров" value={formatMoney(totals.contract, project.currencyCode)} /><Metric label="Оплачено" value={formatMoney(totals.paid, project.currencyCode)} /><Metric label="Остаток" value={formatMoney(totals.remaining, project.currencyCode)} /></div> : <p className="mt-8 border border-border bg-surface p-4 text-sm text-secondary">Финансовые суммы скрыты вашими правами проекта.</p>}
    {notice ? <p className="mt-5 text-sm text-action" role="status">{notice}</p> : null}
    <div className="mt-6 flex flex-col gap-4 border-y border-border py-4 tablet:flex-row tablet:items-end">
      <label className="grid min-w-0 flex-1 gap-2 text-sm font-medium">Поиск<Input data-cy="materials-search" onChange={(event) => setQuery(event.target.value)} placeholder="Название, поставщик, контакт или договор" type="search" value={query} /></label>
      <Select className="tablet:w-56" dataCy="materials-category-filter" label="Категория" onValueChange={setCategory} options={[{ label: "Все категории", value: "all" }, ...categoryOptions]} value={category} />
      <IconButton aria-label={displayMode === "table" ? "Показать материалы списком" : "Показать материалы таблицей"} aria-pressed={displayMode === "list"} className="size-11 shrink-0 border-icon-button-border bg-icon-button text-icon-button-text hover:border-action hover:bg-icon-button-hover" data-cy="materials-display-toggle" onClick={() => setDisplayMode((current) => current === "table" ? "list" : "table")} tooltip={displayMode === "table" ? "Показать списком" : "Показать таблицей"} tooltipAlign="end">{displayMode === "table" ? <ListIcon /> : <TableIcon />}</IconButton>
    </div>
    {list.items.length === 0 ? <Empty canCreate={list.canCreate} onCreate={() => setEditing("new")} /> : visible.length === 0 ? <div className="mt-8 border border-border bg-surface p-8"><h2 className="text-xl font-medium">Ничего не найдено</h2><p className="mt-2 text-sm text-secondary">Измените строку поиска или категорию.</p></div> : displayMode === "table" ? <MaterialTable items={visible} onDelete={setDeleting} onEdit={setEditing} showFinancials={list.canViewFinancialInformation} /> : <MaterialList items={visible} onDelete={setDeleting} onEdit={setEditing} showFinancials={list.canViewFinancialInformation} />}
    <Dialog isOpen={editing !== null} label={editing === "new" ? "Добавление материала" : "Редактирование материала"} onClose={() => setEditing(null)}>{editing ? <MaterialForm expenses={expenses} initial={editing === "new" ? null : editing} onCancel={() => setEditing(null)} onSaved={() => { setEditing(null); setNotice(editing === "new" ? "Материал добавлен." : "Материал обновлён."); void refresh(); }} projectId={projectId} /> : null}</Dialog>
    <Dialog isOpen={deleting !== null} label="Удаление материала" onClose={() => setDeleting(null)}>{deleting ? <DeleteMaterialForm item={deleting} onCancel={() => setDeleting(null)} onDeleted={() => { setDeleting(null); setNotice("Материал удалён из рабочего реестра, история сохранена."); void refresh(); }} projectId={projectId} /> : null}</Dialog>
  </section>;
}

function MaterialTable({ items, onDelete, onEdit, showFinancials }: Readonly<{ items: ProjectMaterial[]; onDelete: (item: ProjectMaterial) => void; onEdit: (item: ProjectMaterial) => void; showFinancials: boolean }>) {
  return <div className="mt-8 overflow-x-auto border border-border bg-surface" data-cy="materials-table"><table className="w-full min-w-[1100px] border-collapse text-left text-sm"><thead><tr className="border-b border-border text-xs uppercase tracking-[0.08em] text-secondary"><th className="p-4">Материал / поставщик</th><th className="p-4">Контакт и договор</th>{showFinancials ? <><th className="p-4">Сумма</th><th className="p-4">Оплачено / остаток</th></> : null}<th className="p-4">Доставка</th><th className="p-4">Связанный расход</th><th className="p-4 text-right">Действия</th></tr></thead><tbody>{items.map((item) => <tr className="border-b border-border align-top last:border-b-0" data-cy={`material-row-${item.id}`} key={item.id}><td className="p-4"><strong className="font-medium">{item.name}</strong><span className="mt-1 block text-secondary">{item.supplierName}</span><span className="mt-2 inline-flex border border-border px-2 py-1 text-xs">{categoryLabel(item.category)}</span></td><td className="max-w-64 p-4 text-secondary"><span className="block break-words">{item.contactInfo || "Контакт не указан"}</span><span className="mt-1 block">{item.contractReference || "Договор не указан"}</span></td>{showFinancials ? <><td className="p-4 font-medium tabular-nums">{formatMoney(item.contractAmountMinor, item.currencyCode)}</td><td className="p-4 tabular-nums"><span className="block text-action">{formatMoney(item.paidAmountMinor, item.currencyCode)}</span><span className="mt-1 block text-secondary">Остаток {formatMoney(item.remainingAmountMinor, item.currencyCode)}</span></td></> : null}<td className="p-4"><span className="inline-flex border border-border px-2 py-1 text-xs">{deliveryLabel(item.deliveryStatus)}</span><span className="mt-2 block text-secondary">{deliveryDate(item)}</span></td><td className="p-4"><MaterialExpenseLink item={item} /></td><td className="p-4"><MaterialActions item={item} onDelete={onDelete} onEdit={onEdit} /></td></tr>)}</tbody></table></div>;
}

function MaterialList({ items, onDelete, onEdit, showFinancials }: Readonly<{ items: ProjectMaterial[]; onDelete: (item: ProjectMaterial) => void; onEdit: (item: ProjectMaterial) => void; showFinancials: boolean }>) {
  return <ul aria-label="Материалы списком" className="mt-8 grid gap-3" data-cy="materials-list">{items.map((item) => <li className="border border-border bg-surface p-5" data-cy={`material-list-item-${item.id}`} key={item.id}><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-medium">{item.name}</h2><span className="inline-flex border border-border px-2 py-1 text-xs">{categoryLabel(item.category)}</span><span className="inline-flex border border-border px-2 py-1 text-xs">{deliveryLabel(item.deliveryStatus)}</span></div><p className="mt-1 text-sm text-secondary">{item.supplierName}</p></div><MaterialActions item={item} onDelete={onDelete} onEdit={onEdit} /></div><dl className="mt-5 grid gap-4 border-t border-border pt-4 text-sm tablet:grid-cols-2 desktop:grid-cols-4"><MaterialDetail label="Контакт" value={item.contactInfo || "Не указан"} /><MaterialDetail label="Договор или счёт" value={item.contractReference || "Не указан"} />{showFinancials ? <><MaterialDetail label="Сумма договора" value={formatMoney(item.contractAmountMinor, item.currencyCode)} /><MaterialDetail label="Оплачено / остаток" value={`${formatMoney(item.paidAmountMinor, item.currencyCode)} / ${formatMoney(item.remainingAmountMinor, item.currencyCode)}`} /></> : null}<MaterialDetail label="Доставка" value={deliveryDate(item)} /><div><dt className="text-xs uppercase tracking-[0.08em] text-secondary">Связанный расход</dt><dd className="mt-1"><MaterialExpenseLink item={item} /></dd></div></dl></li>)}</ul>;
}

function MaterialDetail({ label, value }: Readonly<{ label: string; value: string }>) { return <div><dt className="text-xs uppercase tracking-[0.08em] text-secondary">{label}</dt><dd className="mt-1 break-words">{value}</dd></div>; }
function MaterialExpenseLink({ item }: Readonly<{ item: ProjectMaterial }>) { return item.linkedExpenseId ? <Link className="underline decoration-action underline-offset-4" href={`/account/projects/${encodeURIComponent(item.projectId)}/finances`}>{item.linkedExpenseDescription || "Открыть расход"}</Link> : <span className="text-secondary">Не связан</span>; }
function MaterialActions({ item, onDelete, onEdit }: Readonly<{ item: ProjectMaterial; onDelete: (item: ProjectMaterial) => void; onEdit: (item: ProjectMaterial) => void }>) { return <div className="flex shrink-0 justify-end gap-2"><ContextChatAction chatId={item.contextChatId} contextId={item.id} contextTitle={item.name} contextType="material" projectId={item.projectId} />{item.canEdit ? <IconButton aria-label={`Редактировать ${item.name}`} className="size-9 border-icon-button-border bg-icon-button text-icon-button-text" onClick={() => onEdit(item)} tooltip="Редактировать"><EditIcon /></IconButton> : null}{item.canDelete ? <IconButton aria-label={`Удалить ${item.name}`} className="size-9 border-icon-button-border bg-icon-button text-red-700" onClick={() => onDelete(item)} tooltip="Удалить"><TrashIcon /></IconButton> : null}</div>; }

function MaterialForm({ expenses, initial, onCancel, onSaved, projectId }: Readonly<{ expenses: ProjectExpense[]; initial: ProjectMaterial | null; onCancel: () => void; onSaved: () => void; projectId: string }>) {
  const [category, setCategory] = useState<MaterialCategory>(initial?.category ?? "materials");
  const [name, setName] = useState(initial?.name ?? ""); const [supplier, setSupplier] = useState(initial?.supplierName ?? ""); const [contact, setContact] = useState(initial?.contactInfo ?? ""); const [contract, setContract] = useState(initial?.contractReference ?? "");
  const [amount, setAmount] = useState(initial ? String(initial.contractAmountMinor / 100).replace(".", ",") : ""); const [paymentStatus, setPaymentStatus] = useState<MaterialPaymentStatus>(initial?.paymentStatus ?? "unpaid"); const [deliveryStatus, setDeliveryStatus] = useState<MaterialDeliveryStatus>(initial?.deliveryStatus ?? "expected");
  const [planned, setPlanned] = useState(initial?.plannedDeliveryOn ?? ""); const [actual, setActual] = useState(initial?.actualDeliveryOn ?? ""); const [installation, setInstallation] = useState(initial?.installationOn ?? ""); const [expenseId, setExpenseId] = useState(initial?.linkedExpenseId ?? ""); const [notes, setNotes] = useState(initial?.notes ?? "");
  const [pending, setPending] = useState(false); const [error, setError] = useState("");
  const expenseOptions = [{ label: "Не связывать с расходом", value: "" }, ...expenses.map((expense) => ({ label: `${expense.description} — ${formatMoney(expense.amountMinor, expense.currencyCode)}`, value: expense.id }))] as [{ label: string; value: string }, ...{ label: string; value: string }[]];
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); const amountMinor = parseMoney(amount); if (name.trim().length < 2) { setError("Укажите название материала — минимум 2 символа"); return; } if (supplier.trim().length < 2) { setError("Укажите поставщика — минимум 2 символа"); return; } if (amountMinor === null) { setError("Укажите сумму договора больше нуля"); return; } if (actual && deliveryStatus !== "delivered" && deliveryStatus !== "installed") { setError("Фактическую дату можно указать только для доставленного или установленного материала"); return; }
    const payload: ProjectMaterialInput = { actualDeliveryOn: actual || null, category, contactInfo: contact.trim() || null, contractAmountMinor: amountMinor, contractReference: contract.trim() || null, deliveryStatus, installationOn: installation || null, linkedExpenseId: expenseId || null, name: name.trim(), notes: notes.trim() || null, paymentStatus, plannedDeliveryOn: planned || null, supplierName: supplier.trim() };
    setPending(true); try { if (initial) await updateProjectMaterial(projectId, initial.id, initial.version, payload); else await createProjectMaterial(projectId, payload); onSaved(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Не удалось сохранить материал"); } finally { setPending(false); }
  }
  return <form data-cy="material-form" noValidate onSubmit={submit}><p className="text-xs font-semibold uppercase tracking-[0.14em] text-action">Материалы проекта</p><h2 className="mt-3 font-display text-4xl">{initial ? "Редактировать материал" : "Добавить материал"}</h2>{error ? <p className="mt-5 border border-red-700/40 p-3 text-sm text-red-700" role="alert">{error}</p> : null}<div className="mt-7 grid gap-6 tablet:grid-cols-2"><Select label="Категория" onValueChange={setCategory} options={categoryOptions} required value={category} /><label className="grid gap-2 text-sm font-medium">Название *<Input autoFocus data-cy="material-name" maxLength={300} onChange={(event) => setName(event.target.value)} value={name} /></label><label className="grid gap-2 text-sm font-medium">Поставщик *<Input data-cy="material-supplier" maxLength={200} onChange={(event) => setSupplier(event.target.value)} value={supplier} /></label><label className="grid gap-2 text-sm font-medium">Контактная информация<Input maxLength={500} onChange={(event) => setContact(event.target.value)} value={contact} /></label><label className="grid gap-2 text-sm font-medium">Договор или счёт<Input maxLength={200} onChange={(event) => setContract(event.target.value)} value={contract} /></label><label className="grid gap-2 text-sm font-medium">Сумма договора, ₽ *<Input data-cy="material-amount" inputMode="decimal" onChange={(event) => setAmount(event.target.value)} value={amount} /></label><Select label="Статус оплаты" onValueChange={setPaymentStatus} options={paymentOptions} value={paymentStatus} /><Select label="Статус доставки" onValueChange={setDeliveryStatus} options={deliveryOptions} value={deliveryStatus} /><DatePicker label="Плановая дата доставки" onValueChange={setPlanned} value={planned} /><DatePicker disabled={deliveryStatus !== "delivered" && deliveryStatus !== "installed"} label="Фактическая дата доставки" onValueChange={setActual} value={actual} /><DatePicker label="Дата монтажа" onValueChange={setInstallation} value={installation} /><Select dataCy="material-expense" label="Связанный расход" onValueChange={setExpenseId} options={expenseOptions} value={expenseId} /><label className="grid gap-2 text-sm font-medium tablet:col-span-2">Примечание<Textarea maxLength={5000} onChange={(event) => setNotes(event.target.value)} value={notes} /></label></div><div className="mt-7 flex flex-wrap gap-3"><Button data-cy="save-material" disabled={pending} type="submit">{pending ? "Сохраняем…" : initial ? "Сохранить" : "Добавить материал"}</Button><Button onClick={onCancel} type="button" variant="secondary">Отмена</Button></div></form>;
}

function DeleteMaterialForm({ item, onCancel, onDeleted, projectId }: Readonly<{ item: ProjectMaterial; onCancel: () => void; onDeleted: () => void; projectId: string }>) { const [reason, setReason] = useState(""); const [pending, setPending] = useState(false); const [error, setError] = useState(""); async function submit(event: FormEvent) { event.preventDefault(); if (reason.trim().length < 2) { setError("Укажите причину удаления"); return; } setPending(true); try { await deleteProjectMaterial(projectId, item.id, item.version, reason.trim()); onDeleted(); } catch (value) { setError(value instanceof Error ? value.message : "Не удалось удалить материал"); } finally { setPending(false); } } return <form onSubmit={submit}><h2 className="font-display text-4xl">Удалить «{item.name}»?</h2><p className="mt-3 text-sm leading-6 text-secondary">Материал исчезнет из рабочего реестра, но версия и причина удаления останутся в аудите.</p>{error ? <p className="mt-5 text-sm text-red-700" role="alert">{error}</p> : null}<label className="mt-6 grid gap-2 text-sm font-medium">Причина удаления *<Textarea autoFocus maxLength={500} onChange={(event) => setReason(event.target.value)} value={reason} /></label><div className="mt-6 flex gap-3"><Button disabled={pending} type="submit">{pending ? "Удаляем…" : "Удалить"}</Button><Button onClick={onCancel} type="button" variant="secondary">Отмена</Button></div></form>; }

function Metric({ label, value }: Readonly<{ label: string; value: string }>) { return <div className="bg-surface p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.08em] text-secondary">{label}</p><p className="mt-2 font-display text-3xl tabular-nums">{value}</p></div>; }
function Empty({ canCreate, onCreate }: Readonly<{ canCreate: boolean; onCreate: () => void }>) { return <div className="mt-8 border border-border bg-surface p-8" data-cy="materials-empty"><h2 className="text-xl font-medium">Материалов пока нет</h2><p className="mt-2 max-w-xl text-sm text-secondary">Добавьте первую позицию, чтобы вести поставщика, договор, оплату и доставку в одном месте.</p>{canCreate ? <IconButton aria-label="Добавить первый материал" className="mt-5 size-10 border-icon-button-border bg-icon-button text-icon-button-text hover:border-action hover:bg-icon-button-hover" onClick={onCreate} tooltip="Добавить материал" tooltipAlign="start"><PlusIcon /></IconButton> : null}</div>; }
function categoryLabel(value: MaterialCategory) { return categoryOptions.find((item) => item.value === value)?.label ?? value; }
function deliveryLabel(value: MaterialDeliveryStatus) { return deliveryOptions.find((item) => item.value === value)?.label ?? value; }
function deliveryDate(item: ProjectMaterial) { const value = item.actualDeliveryOn || item.plannedDeliveryOn; if (!value) return "Дата не указана"; return `${item.actualDeliveryOn ? "Факт" : "План"}: ${new Intl.DateTimeFormat("ru-RU", { dateStyle: "medium" }).format(new Date(`${value}T00:00:00`))}`; }
function PlusIcon() { return <svg aria-hidden="true" className="size-4" fill="none" viewBox="0 0 24 24"><path d="M12 5v14M5 12h14" stroke="currentColor" strokeLinecap="round" strokeWidth="1.7" /></svg>; }
function ListIcon() { return <svg aria-hidden="true" className="size-4" fill="none" viewBox="0 0 20 20"><path d="M7 5h10M7 10h10M7 15h10M3 5h.01M3 10h.01M3 15h.01" stroke="currentColor" strokeLinecap="round" strokeWidth="1.6" /></svg>; }
function TableIcon() { return <svg aria-hidden="true" className="size-4" fill="none" viewBox="0 0 20 20"><rect height="12" width="14" x="3" y="4" stroke="currentColor" strokeWidth="1.4"/><path d="M3 8h14M3 12h14M8 4v12" stroke="currentColor" strokeWidth="1.2"/></svg>; }
function EditIcon() { return <svg aria-hidden="true" className="size-4" fill="none" viewBox="0 0 24 24"><path d="m4 16-.5 4.5L8 20l11-11-4-4L4 16Z" stroke="currentColor" strokeLinejoin="round" strokeWidth="1.5" /></svg>; }
function TrashIcon() { return <svg aria-hidden="true" className="size-4" fill="none" viewBox="0 0 24 24"><path d="M5 7h14M9 7V4h6v3m-8 0 1 13h8l1-13M10 11v5m4-5v5" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" /></svg>; }
